### ISSUE TITLE
Fix deployment

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/balancer-main#132]
The latest deployment of Balancer on CfP's sandbox cluster failed to stage after CodeForPhilly/cfp-sandbox-cluster#65 was merged: https://github.com/CodeForPhilly/cfp-sandbox-cluster/actions/runs/8904132821

The issue is that the target branch was switched from `develop` to `helm-chart-3`—but the `helm-chart-3` branch is missing the `.holo/` directory that is present in the `develop` branch. This directory defines a virtual target called `helm-chart` that defines a set of files to export from the repository, which happens in this case just to be everything inside the root `helm-chart` directory (some projects are laid out differently, and this layer enables projects to map what they publish to their existing layout)

**Comment by themightychris** [comment]
That initial issue was fixed, exposing now that there's a syntax error in the Helm YAML.

You can test/debug this locally if you have the `helm` v3 command installed:

```console
$ helm template --namespace balancer --release-name balancer helm-chart
Error: template: helm-chart/templates/nginx-configmap.yaml:56:29: executing "helm-chart/templates/nginx-configmap.yaml" at <.Values.frontend.server_name>: nil pointer evaluating interface {}.server_name

Use --debug flag to render out invalid YAML
```

**Comment by joshuagerstein** [comment]
It works when I do `helm template --namespace balancer --release-name balancer helm-chart --values=helm-chart/Values.yaml`

**Comment by themightychris** [comment]
Deployment successfully staged: https://github.com/CodeForPhilly/cfp-sandbox-cluster/pull/66
