### ISSUE TITLE
Ungroup reproductive checkboxes

### ISSUE THREAD

**Issue by katjost** [CodeForPhilly/balancer-main#156]
Instead of:

![Image](https://github.com/user-attachments/assets/9b600bd3-4968-4db7-be69-038c651dc849)

Show two additional rows of radio buttons:

- Any possibility of becoming pregnant (Y/N)
- Wants to conceive in next 2 years (Y/N)

Please reach out to Kat with any questions.

**Comment by mandyshri101** [comment]
Thanks @katjost Will look into it.

**Comment by katjost** [comment]
Need to add back the missing reproductive question.

**Comment by mandyshri101** [comment]
@katjost and @taichan03: Would need your help in reversing back the exact question we had to put. Let me also look into GitHub if I can point out the old repo. Thank you.

**Comment by mandyshri101** [comment]
@katjost and @taichan03: Is it okay for me to close this ticket if this has been merged? Please advise.

**Comment by taichan03** [comment]
yes
