### ISSUE TITLE
Change Help page icons' color to match font color

### ISSUE THREAD

**Issue by taichan03** [CodeForPhilly/balancer-main#90]
![Image](https://github.com/CodeForPhilly/balancer-main/assets/64656587/601a9257-5422-448b-8b97-9c530702f4fe)

On the Help page, the current icons are a dark blue. I think it would look nicer if they matched the blue from the font / logo.

**Comment by katjost** [comment]
Removed assignee as we have not seen them in a while. Anyone can pick this up!

**Comment by snaeem3** [comment]
I can help with this task. I also noticed some unnecessary `useState` and `useEffect` code in Help.tsx and HelpCard.tsx that can be removed to potentially improve performance.

**Comment by katjost** [comment]
@snaeem3 this is great. Thank you.

> I can help with this task. I also noticed some unnecessary useState and useEffect code in Help.tsx and HelpCard.tsx that can be removed to potentially improve performance.
Yes, please go ahead and remove the unnecessary code. Great catch!

> I would also like to know if the Line Chart svg icon in the /data-sources page should also match the font color or stay the same.
Yes, that's another great catch! Thank you.
